language: ruby
rvm:
  - 2.1.2
  - 2.0.0
  - 1.9.3
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y swig
  - git clone https://github.com/cmusphinx/sphinxbase.git
  - cd sphinxbase
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - cd ..
  - git clone https://github.com/cmusphinx/pocketsphinx.git
  - cd pocketsphinx
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - cd ..
  - sudo ldconfig